name: discord-notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - stg
      - main
    types: [opened, edited, reopened, synchronize]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  command:
    name: Use Actions Status Discord
    runs-on: ubuntu-20.04
    steps:
      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            **Event:** ${{ github.event_name }}
            **Type:** ${{ github.event.pull_request && 'Pull Request' || (github.event.issue && github.event.issue.pull_request && 'Pull Request Comment') || 'Issue' }}
            **Title:** ${{ github.event.pull_request.title || github.event.issue.title }}
            **Action:** ${{ github.event.action }}
            **Link:** ${{ github.event.pull_request.html_url || github.event.comment.html_url || github.event.issue.html_url }}
            **User:** ${{ github.event.comment.user.login || github.event.review.user.login || github.event.pull_request.user.login || github.event.issue.user.login }}
            **${{ github.event_name == 'issue_comment' && 'Comment' || github.event.review && 'Review' || 'Description' }}:**
            ```
            ${{ github.event.comment.body || github.event.review.body || github.event.pull_request.body || github.event.issue.body }}
            ```
