name: discord-notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - stg
      - main
    types: [opened, edited, reopened, synchronize] # PRのアクションを捕捉
  pull_request_review: # レビューが提出されたとき
    types: [submitted]
  issue_comment: # PRのコメントを捕捉
    types: [created]

jobs:
  command:
    name: Use Actions Status Discord
    runs-on: ubuntu-20.04
    steps:
      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always() && (github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'stg')
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ${{ github.event.pull_request.title }} - ${{ github.event.action }} 
            @ [PR リンク](${{ github.event.pull_request.html_url }}) 

            ${{ github.event.comment.body }} # コメントの内容も含める
