name: discord-notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - stg
      - main
    types: [opened, edited, reopened, synchronize]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  command:
    name: Use Actions Status Discord
    runs-on: ubuntu-20.04
    steps:
      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            Event: ${{ github.event_name }}
            ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && 'PR Comment' || github.event.pull_request && 'Pull Request' || 'Issue' }}: ${{ github.event.pull_request.title || github.event.issue.title }}
            Action: ${{ github.event.action }}
            ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && 'PR' || 'Issue' }} Link: ${{ github.event.pull_request.html_url || github.event.issue.html_url }}
            ${{ github.event.comment && 'Comment by' || github.event.review && 'Review by' || 'Created by' }}: ${{ github.event.comment.user.login || github.event.review.user.login || github.event.pull_request.user.login || github.event.issue.user.login }}

            ${{ github.event.comment && 'Comment' || github.event.review && 'Review' || 'Description' }}:
            ```
            ${{ github.event.comment.body || github.event.review.body || github.event.pull_request.body || github.event.issue.body }}
            ```
